### ISSUE TITLE
Logo position in left top corner

### ISSUE THREAD

**Issue by ArthurData** [dsbbfinddx/finddxtemplate#1]
Put logo in left top corner, on top of table of content, similar to FIND website and also resize similarly to the one in website.

On the website:
```css
.header-logo a, .header-logo img {
  width: 154px;
  height: 53px;
}
```
